unstable_features = true

indent_style = "Block"
reorder_imports = true

blank_lines_lower_bound = 1
brace_style = "SameLineWhere"

color = "Always"

fn_args_layout = "Vertical"
fn_single_line = true

enum_discrim_align_threshold = 20

force_explicit_abi = true

format_strings = true


