name: Rust

on:
  push:
    branches: [ "master","dev" ]
  pull_request:
    branches: [ "master","dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
            
    - name: Adding rust-src to project
      run: rustup component add rust-src
      
    - name: Build
      uses: actions-rs/cargo@v1 
      with:
        command: build
        args: --verbose
        
    - name: Run test in basic boot
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose -- --test basic_boot
        
    - name: Run test in should panic
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose -- --test should_panic
        
    - name: Formatation check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check
        
    - name: Clippy check
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
